# Generated by Django 5.0.7 on 2024-08-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phothography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('legend', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=150)),
            ],
        ),
    ]
